{{- if eq .Release.Service "CLI" -}}
---
kind: Namespace
apiVersion: v1
metadata:
  name: {{.Release.Namespace}}
  labels:
    linkerd.io/extension: jaeger
    {{- /* linkerd-init requires extended capabilities and so requires priviledged mode */}}
    pod-security.kubernetes.io/enforce: {{ ternary "restricted" "privileged" .Values.cniEnabled }}
{{ end -}}
